### ISSUE TITLE
Belkis: student's bio

### ISSUE THREAD

**Issue by mametur** [HYF-Class21/home#51]
- [x] My bio file is named _exactly_ the same as my GitHub username
- [x] My `bio` link in the class README opens to my student bio file
- [x] I pulled and merged `main` into my branch before pushing
- [x] I pushed my branch to the class repository and opened a PR
- [x] I went through the PR checklist
- [x] All the CI check pass
- [x] I assigned a coach to review my PR
- [x]  [linked my PR to this issue]()

**Comment by blksck** [comment]
Can you please check my last changes?
