### ISSUE TITLE
juhar:Agile development:4 weeks

### ISSUE THREAD

**Issue by Juharzeynu** [HYF-Class21/home#96]
- [ ] Learning Objectives

- [x] Developing HTML & CSS

   

- [x]  VSCode:

- [x] - Use the LiveServer extension to launch an HTML page in the browser

- [x] - Use autocomplete to begin a new HTML document, create new tags

- [x] - Use the HTML CSS Support and IntelliSense fo CSS class names extensions to make writing HTML & CSS more efficient.

- [x] - Formatting HTML & CSS:

- [x] - Use VSCode configurations to format my code on save

- [x] - Use npm run format to format all the code in my repository

- [x] - Linting CSS:

- [ ] - Use the npm run lint:css script to find mistakes in my CSS, and I can fix the mistakes.

- [x] - Validating HTML:

- [x] - Use the npm run validate:html script to find mistakes in your CSS, and I can fix the mistakes.

- [ ] - Browser Developer Tools:

- [x] - Inspect the source code of a web page using the Sources tab

- [ ] - Find any part of the web page in the Elements tab of my Dev Tools DOM inspector

- [x] - Find the styles for any element in the Elements tab

- [ ] - Make temporary changes in a web page from the Elements tab to see how they will look

- [x] - Following Plans:

- [x] - Project Definition and Scope

- [x] - Project Constraints

- [x] - Communication Plans

- [ ] - Communicating Challenges

- [x] - Using a Backlog

- [ ] - Follow a Development Strategies

- [x] - Create Issues From a Dev Strategy

- [x] - Retrospective:

- 

- [ ] How well I worked as a group

- [ ] - Find ways to improve in the next project

- [ ] - Compare my plan to the reality of developing your website.

- [ ] - Claiming and Completing Issues:

- [ ] - I can claim issues from the TODO column of a project board and track your progress with the project board

- [ ] - Develop my code locally on a separate branch

- [ ] - Send a PR that passes CI checks and meets the requirements.

- [ ] - Code Review: I can both review a group mate's PR, and productively participate in a review of my own code.

- [ ] - Match a Design & Acceptance Criteria

- [ ] - Writing Plans

- 

- [x] Write User Personas

- [x] - Write User Stories

- [x] - Write a Backlog

- [x] - Create a Prioritized Design

- [ ] - Write a Development Strategies

- Week X

- [ ] I have pushed my progress to [my fork of exercises repo](_)

## I Need Help With:
i need help  in html and css  coding and planing
## What went well?
not that much
## Lessons Learned
i learned how to work with group 
## Sunday Prep Work
see you
---- END CHECK-IN TEMPLATE ---->

**Comment by Moamin-AbuEwaida** [comment]
@Juharzeynu  normally the `checked-1` label added by the coach who checks your issue

**Comment by sammou00** [comment]
@Juharzeynu You already have an issue for this module, why did you create a new one?
